on:
  wurmberg_amtsblatt:
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        run: |
          echo "id:    ${{ on.wurmberg_amtsblatt.outputs.id }}"
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_WURMBERGBOT_TO }}
          token: ${{ secrets.TELEGRAM_WURMBERGBOT_TOKEN }}
          message: |
            Neues Amtsblatt: ${{ on.wurmberg_amtsblatt.outputs.title }}
            => ${{ on.wurmberg_amtsblatt.outputs.url }}
