on:
  local_trigger_test:
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        run: |
          echo "id:    ${{ on.local_trigger_test.outputs.id }}"
          echo "title: ${{ on.local_trigger_test.outputs.title }}"
